server:
  port: 80
zuul:
  routes:
    courses:
      path: /courses-management/**
      serviceId: courses-service

spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url.default: http://localhost:8761/eureka

